### ISSUE TITLE
4.08 support broken (`List.concat_map`)

### ISSUE THREAD

**Issue by bclement-ocp** [Gbury/dolmen#195]
#190 uses `List.concat_map` which is not available on OCaml 4.08 (introduced in 4.10).

Found by Alt-Ergo's CI here: https://github.com/OCamlPro/alt-ergo/actions/runs/6532270561/job/17735127849?pr=893

**Comment by Gbury** [comment]
Ah that's annoying indeed.

For the context: CI does not test `4.08` anymore because the `model` part depends on `farith` which introduces a dependency on `ocaml >= 4.10`. However, the parsing and typing part of the library actually still build with `4.08`, even if we cannot actually test them (because most of the tests require the `bin` part which depends on the `model` part).

**Comment by Halbaroth** [comment]
We may use `stdcompat`?

**Comment by Gbury** [comment]
> We may use `stdcompat` as we did in AE now? I can do it if you want :)

It's not the problem: the fix in the code is trivial (and dolmen already re-implements quite a few usual functions for lists here and there). The point is rather how to setup things so that the CI can check that things build with `4.08` (that one is relatively easy) and if possible that it behaves correctly, i.e. that the tests pass (that one is trickier, as explained above).

**Comment by Halbaroth** [comment]
You don't want to bump the minimal version to `4.10`? If the `model` part of `Dolmen` isn't a separated library, it will be painful to test the remainder part on `4.08`.

**Comment by Gbury** [comment]
That's the easy solution, but is that okay for alt-ergo ?

**Comment by Halbaroth** [comment]
I don't know. We ask if it's okay for Why3 ;)

**Comment by bclement-ocp** [comment]
Why? Why3 does not depend on alt-ergo.

**Comment by Gbury** [comment]
In any case, I just pushed baaf1f92ccd473294679dd9025c3ae9a441a82fa to `master` which should solve the build issue on `4.08` for now. Ill continue and try to think if/how to best support versions of ocaml `< 4.10` for the parsing library.

**Comment by bclement-ocp** [comment]
FWIW `list_concat_map` was already defined in `src/standard/expr.ml`

**Comment by Gbury** [comment]
woops
