### ISSUE TITLE
bv2nat is not recognized 

### ISSUE THREAD

**Issue by yannickmoy** [Gbury/dolmen#94]
With the latest version of dolmen installed through opam, as well as the released binary, I'm getting an error on use of `bv2nat`:

```
dolmen bv.smt2
File "./bv.smt2", line 7, character 11-24:
Error Unbound identifier: `bv2nat`
```

on the file:

```
(set-info :smt-lib-version 2.6)
(set-logic AUFBVDTNIRA)

(declare-const bvec (_ BitVec 32))
(declare-const ival Int)

(assert (= (bv2nat bvec) ival))
```

Is it expected? That might be an issue for submitting benchmarks to the SMT-COMP, as dolmen is used as a PR check. Also, I see that `dolmen --version` is returning 0.1, while I would have expected 0.6, so is that a setup issue somewhere on my side? TIA

**Comment by Gbury** [comment]
The version thing is just me forgetting to update the version number in the `cli` description for `dolmen` apologies for that, i'll try and fix that (at least for future versions, it might not be worth it to fix older releases), ^^

For the `bv2nat`, I'd say it's expected. Indeed, as specified in the [theory definition for bitvector](https://smtlib.cs.uiowa.edu/theories-FixedSizeBitVectors.shtml):

> 
>   To define some of the semantics below, we need the following additional
>    functions :
> 
>    o _ div _,  which takes an integer x ≥ 0 and an integer y > 0 and returns
>      the integer part of x divided by y (i.e., truncated integer division).
> 
>    o _ rem _, which takes an integer x ≥ 0 and y > 0 and returns the
>      remainder when x is divided by y.  Note that we always have the following
>      equivalence for y > 0: (x div y) * y + (x rem y) = x.
> 
>    o bv2nat, which takes a bitvector b: [0, m) → {0, 1}
>      with 0 < m, and returns an integer in the range [0, 2^m),
>      and is defined as follows:
> 
>        bv2nat(b) := b(m-1)*2^{m-1} + b(m-2)*2^{m-2} + ⋯ + b(0)*2^0

From what I understand, this means that `bv2nat` is **not** a regular function defined by the theory and usable in scripts, but is only defined in the semantics part of the theory, to give meaning to the functions defined by the theory (just like the `div` and `rem` "additional functions" are not functions one can use in a script that only uses the bitvector theory).

**Comment by hansjoergschurr** [comment]
I remember a similar discussion about `fp.to_real` which is only useful if the theory contains real numbers in addition to floating points.  Hence, back then I think we added LRA to the affected benchmarks.
The situation might be different with bitvectors though.

**Comment by Gbury** [comment]
Indeed the situation is more or less similar, except that the FP theory defines the `Real` sort and the `fp.to_real` function officially (whereas, as far as I can tell, the BV theory does not define the `bv2nat` function outside its semantics section (also, note that it would be badly named, as considering the smtlib sort is `Int` and not `Nat`, it'd make more sens to call it `bv2int`, or event `bv.to_int`)).

Talking about that, such conversions functions actually only make sens when the two relevant theories are actually used, and maybe smtlibv3 could improve on that (by defining either specific theory intersection/unions ? or rather by defining dependencies between theories so that using `BV` automatically also brings in at least `LIA` ?), in any case, this is a bit off-topic for this discussion here, so maybe that particular point would be better suited to a discussion on the smtlib mailing list/google group I suppose.

That begin said, I'd still like for an SMTLIB maintainer to clarify whether `bv2nat` is actually defined by the `BV` theory and usable as a function in scripts.

**Comment by yannickmoy** [comment]
@mpreiner thanks for the answer. I've regenerated the benchmark for SMT-COMP so that each occurrence of `bv2nat` is now a call to a properly defined `bv2natnnn` for all sizes `nnn` of BV that we are using (8, 16, 32, 64, 128 and 256). On simple VCs, it does not seem to change a thing for CVC4 or Z3. As this was only for submitting this benchmark, I have no more use for adding `bv2nat` in SMT-LIB, unless you think that the explicit definitions will impact provability?
